### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by ABgitme**
hi azeez check this get and count functionality added

### CODE REVIEW

**Comment by ABgitme** [comment]
get and count method

**Comment by ABgitme** [comment]
update get and count added

**Review by azeez-abp — APPROVED** [review]
Merge done

**Comment by azeez-abp** [comment]
Merge completed

**Review by azeez-abp — APPROVED** [review]

**Review by azeez-abp — APPROVED** [review]

**Review by azeez-abp — APPROVED** [review]

**Review by azeez-abp — APPROVED** [review]

**Comment by ABgitme** [comment]
updated count method

**Pull request merged**
